spring:
  application:
    name: test-actuator

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
