version: "2"
services:
  node-exporter:
    image: prom/node-exporter:v1.3.0
    container_name: node-exporter
    ports:
      - "9100:9100"

  spring-boot:
    build: ./test-actuator
    container_name: spring-boot
    ports:
      - "8080:8080"

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
    links:
      - node-exporter
      - spring-boot
      - black-box
      - alert-manager
    depends_on:
      - node-exporter
      - spring-boot
      - alert-manager
      - black-box

  grafana:
    image: grafana/grafana:8.3.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    links:
      - node-exporter

  alert-manager:
    image: prom/alertmanager:v0.23.0
    container_name: alert-manager
    ports:
      - "9300:9300"
      - "9093:9093"

  black-box:
    image: prom/blackbox-exporter:v0.19.0
    container_name: black-box
    ports:
      - "9115:9115"
